service: project-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    DB_HOST : tr-course-rds-instance.coafej8tch0x.eu-west-2.rds.amazonaws.com
    DB_USER : root
    DB_PASSWORD : walden31
    DB_SCHEMA : petloves

functions:
  pets:
    handler: handler.pets
    events:
      - http:
          path: pets
          method: get
          cors: true
